{
  'code-block-style': { 'style': 'fenced' },
  'code-fence-style': { 'style': 'backtick' },
  'emphasis-style': { 'style': 'asterisk' },
  'heading-style': { 'style': 'atx' },
  'hr-style': { 'style': '---' },
  'line-length': false,
  'no-duplicate-heading': { 'siblings_only': true },
  'ol-prefix': { 'style': 'ordered' },
  'strong-style': { 'style': 'asterisk' },
  'table-pipe-style': { 'style': 'leading_and_trailing' },
  'ul-style': { 'style': 'dash' },
  'blank_lines': false,
  'ul': false,
  'no-trailing-punctuation': false,
  'ol': false,
  'emphasis': false,
  'no-inline-html': false,
  'MD041': true,
  'MD028': false,
}
